[package]
name = "polars"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.45.0", features = ["csv", "ipc", "parquet"] }
anyhow = "1.0"
rand = "0.8"

[[bin]]
name = "polars"
path = "code/polars_example.rs"

[build]
target-dir = "rust-target"
